<a href="https://colab.research.google.com/github/szymonszwedzinskiii/DataTemplates/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
N, D = 200, 2
SEED = 54321
X,y = datasets.make_classification(n_samples=N,n_features=D,n_informative=2,n_redundant=0,random_state=SEED)

X = np.reshape(X, (N, D))
y = np.reshape(y, (N, 1))

In [3]:
df = pd.DataFrame({
    "X_1": X[:,0],
    "X_2":X[:,1],
    "label": ["positive" if y_i>0 else "negative" for y_i in y]
},index = list(range(N)))

df

          X_1       X_2     label
0    1.434174 -0.593742  negative
1   -0.546980 -1.061760  negative
2    0.651044  0.868971  positive
3    0.249456 -1.033361  negative
4   -1.047607 -0.693791  negative
..        ...       ...       ...
195 -0.922138 -2.105524  negative
196 -1.309470  0.949647  positive
197  0.617753  0.751026  positive
198 -1.028913 -1.058349  negative
199  0.267971  2.973200  positive

[200 rows x 3 columns]

In [4]:
import plotly.express as px

In [5]:
px.scatter(df,x="X_1", y="X_2",color="label")

In [6]:
def sigmoid(x):
  x = np.clip(x,-500,500)
  return 1/(1 + np.exp(-x))

In [7]:
w= np.array([1.0,2.0])
b = 3.0

w = np.reshape(w, (D,1))

In [22]:
def model(x,w,b):
  logits = np.matmul(x,w) + b
  return sigmoid(logits)

#y_pred = model(X,w,b)
#print(f" ypred= {list(y_pred)}\n target = {list(y)}")

In [23]:
def plot(w,b):
  import plotly.graph_objects as go
  def get_points(w,b,x1,x2):
    A,B = w[0,0], w[1,0]
    C= b
    return {
        "x":[x1,x2],
        "y":[(C-A*x1)/B, (C-A*x2)/B]
    }
  fig1 = px.scatter(df,x='X_1',y="X_2",color="label")
  fig2= go.Figure(go.Scatter(**get_points(w,b,-2,4), name="brzeg"))
  return go.Figure(data=fig1.data + fig2.data)

In [24]:
plot(w,b)

In [25]:
def cross_entropy(y_pred,target):
  epsilon = 1e-15
  y_pred = np.clip(y_pred,epsilon,1-epsilon)
  if target.ndim==1:
    target = target.reshape(-1,1)
  return -np.mean(target * np.log(y_pred) + (1-target) * np.log(1-y_pred))

In [26]:
def compute_costs(X,y,w,b):
  y_pred = model(X,w,b)
  return cross_entropy(y_pred,y)

In [27]:
compute_costs(X,y,w,b)

np.float64(1.027921502033809)

In [28]:
def compute_gradient(X,y,w,b):
  n = len(X)
  y_pred = model(X,w,b)
  dw = (1/n) * np.matmul(X.T,(y_pred-y))
  db = (1/n) * np.sum(y_pred-y)
  return dw,db

In [29]:
compute_gradient(X,y,w,b)

(array([[ 0.20607611],
        [-0.15604127]]),
 np.float64(0.294252928552664))

In [30]:
def step_gradient(data_x, data_y,w_current,b_current,alpha):
  dw,db = compute_gradient(data_x,data_y,w_current,b_current)
  w_new = w_current - alpha * dw
  b_new = b_current - alpha * db
  return w_new,b_new

In [31]:
w_before, b_before = w,b
cost_before = compute_costs(X,y,w_before,b_before)
w_after, b_after = step_gradient(X,y,w_before,b_before,0.1)
cost_after = compute_costs(X,y,w_after,b_after)
print(f"cost before = {cost_before}\n cost after = {cost_after}")

cost before = 1.027921502033809
 cost after = 1.0126587031707026

In [32]:
w_before, b_before = w,b
cost_before = compute_costs(X,y,w_before,b_before)
w_after, b_after = step_gradient(X,y,w_before,b_before,1.0)
cost_after = compute_costs(X,y,w_after,b_after)
print(f"cost before = {cost_before}\n cost after = {cost_after}")

cost before = 1.027921502033809
 cost after = 0.8823548482348891

In [19]:
print(w_before,b_before)
print(w_after,b_after)

[[1.]
 [2.]] 3.0
[[0.79392389]
 [2.15604127]] 2.705747071447336

Plot before 1 step

---

In [33]:
plot(w_after,b_after)

Plot after 1 step

In [34]:
plot(w_before,b_before)

In [35]:
def training(data_x,data_y,w_init,b_init,alpha,num_eopchs):
  w=w_init
  b = b_init

  cost_history=[]

  w_history=[]
  b_history =[]
  for i in range(num_eopchs):
    cost_history.append(compute_costs(data_x,data_y,w,b))
    w_history.append(w)
    b_history.append(b)
    w,b = step_gradient(data_x,data_y,w,b,alpha)
    cost = compute_costs(data_x,data_y,w,b)
    cost_history.append(cost)
  return cost_history, w_history,b_history

In [36]:
cost_history, w_history,b_history = training(X,y,w,b,0.1,20)
print(f'first cost = {cost_history[0]}, cost after 20 epochs and alpha =0.01 = {cost_history[-1]}')

first cost = 1.027921502033809, cost after 20 epochs and alpha =0.01 = 0.773223216434235

In [37]:
cost_history, w_history,b_history = training(X,y,w,b,0.1,100)
print(f'first cost = {cost_history[0]}, cost after 100 and alpha =0.01 epochs = {cost_history[-1]}')

first cost = 1.027921502033809, cost after 100 and alpha =0.01 epochs = 0.3783349737244731

In [38]:
cost_history, w_history,b_history = training(X,y,w,b,1,20)
print(f'first cost = {cost_history[0]}, cost after 20 epochs and alpha =1 = {cost_history[-1]}')

first cost = 1.027921502033809, cost after 20 epochs and alpha =1 = 0.29649513318300824

Plot for trained data with cost ~0.2964

In [39]:
plot(w_history[-1],b_history[-1])

plot for not trained data

In [40]:
plot(w,b)

In [58]:
df = pd.read_csv('/content/Crop_recommendation.csv')
df

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [43]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [57]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y.reshape(-1,1))
scaler = StandardScaler()
X = scaler.fit_transform(X)
print(y)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [45]:
def softmax(z):
  z= np.clip(z,-500, 500)
  exp_z=np.exp(z)
  return exp_z/np.sum(exp_z,axis=1,keepdims=True)

In [46]:
def model_m(x,w,b):
  logits = np.matmul(x,w) + b
  return softmax(logits)

In [47]:
def cross_entropy_m(y_pred,target):
  epsilon = 1e-15
  y_pred = np.clip(y_pred,epsilon,1-epsilon)
  return -np.mean(np.sum(target * np.log(y_pred),axis =1))

In [48]:
def compute_gradient_m(X,y,w,b):
  n = len(X)
  y_pred = model_m(X,w,b)
  dw = (1/n) * np.matmul(X.T,(y_pred-y))
  db = (1/n) * np.sum(y_pred-y)
  return dw,db

In [49]:
def step_gradient_m(data_x, data_y,w_current,b_current,alpha):
  dw,db = compute_gradient_m(data_x,data_y,w_current,b_current)
  w_new = w_current - alpha * dw
  b_new = b_current - alpha * db
  return w_new,b_new

In [50]:
def compute_costs_m(X,y,w,b):
  y_pred = model_m(X,w,b)
  return cross_entropy_m(y_pred,y)

In [51]:
def training(data_x,data_y,w_init,b_init,alpha,num_eopchs):
  w=w_init
  b = b_init

  cost_history=[]

  w_history=[]
  b_history =[]
  for i in range(num_eopchs):
    cost_history.append(compute_costs_m(data_x,data_y,w,b))
    w_history.append(w)
    b_history.append(b)
    w,b = step_gradient_m(data_x,data_y,w,b,alpha)
    cost = compute_costs_m(data_x,data_y,w,b)
    cost_history.append(cost)
  return cost_history, w_history,b_history

In [52]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [53]:
epochs = 10000
alpha = 0.01

cost_history, w_history,b_history = training(X_train,y_train,w_init=np.zeros((X_train.shape[1],22)),b_init=0,alpha=alpha,num_eopchs=epochs)
print(f'first cost = {cost_history[0]}, cost after {epochs} and alpha ={alpha} epochs = {cost_history[-1]}')

y_pred = model_m(X_test,w_history[-1],b_history[-1])

cost = compute_costs(X_test,y_test,w_history[-1],b_history[-1])
print(f"cost = {cost}")

first cost = 3.091042453358315, cost after 100000 and alpha =0.01 epochs = 0.201794991729353
cost = 1.9203702397559665

In [54]:
X.shape

(2200, 7)

In [66]:
X

X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [67]:
X

array([[ 90.        ,  42.        ,  43.        , ...,  82.00274423,
          6.50298529, 202.9355362 ],
       [ 85.        ,  58.        ,  41.        , ...,  80.31964408,
          7.03809636, 226.6555374 ],
       [ 60.        ,  55.        ,  44.        , ...,  82.3207629 ,
          7.84020714, 263.9642476 ],
       ...,
       [118.        ,  33.        ,  30.        , ...,  67.22512329,
          6.36260785, 173.3228386 ],
       [117.        ,  32.        ,  34.        , ...,  52.12739421,
          6.75879255, 127.1752928 ],
       [104.        ,  18.        ,  30.        , ...,  60.39647474,
          6.77983261, 140.9370415 ]])

In [61]:
print(df)

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [77]:
df.drop(columns=['ph'])
labels = df['label'].unique()
print(labels)

['rice' 'maize' 'chickpea' 'kidneybeans' 'pigeonpeas' 'mothbeans'
 'mungbean' 'blackgram' 'lentil' 'pomegranate' 'banana' 'mango' 'grapes'
 'watermelon' 'muskmelon' 'apple' 'orange' 'papaya' 'coconut' 'cotton'
 'jute' 'coffee']

In [74]:
rice = df.loc[df['label'] == 'rice']
print(rice.describe())

                N           P           K  temperature    humidity  \
count  100.000000  100.000000  100.000000   100.000000  100.000000
mean    79.890000   47.580000   39.870000    23.689332   82.272822
std     11.917981    7.904966    2.946167     2.031272    1.418381
min     60.000000   35.000000   35.000000    20.045414   80.122675
25%     69.000000   41.000000   38.000000    21.927064   80.952094
50%     80.000000   47.000000   40.000000    23.734837   82.189357
75%     91.000000   54.250000   42.000000    25.513702   83.470254
max     99.000000   60.000000   45.000000    26.929951   84.969072

               ph    rainfall
count  100.000000  100.000000
mean     6.425471  236.181114
std      0.768692   34.291825
min      5.005307  182.561632
25%      5.869992  204.334023
50%      6.363804  233.119859
75%      7.039147  264.126903
max      7.868475  298.560117

In [75]:
coffee = df.loc[df['label'] == 'coffee']
print(coffee.describe())

                N           P           K  temperature    humidity  \
count  100.000000  100.000000  100.000000   100.000000  100.000000
mean   101.200000   28.740000   29.940000    25.540477   58.869846
std     12.345203    7.276113    3.246817     1.502635    5.838566
min     80.000000   15.000000   25.000000    23.059519   50.045570
25%     89.000000   23.000000   27.000000    24.218563   53.814433
50%    103.000000   29.000000   30.000000    25.656643   57.648083
75%    112.000000   34.250000   33.000000    26.744956   63.579586
max    120.000000   40.000000   35.000000    27.923744   69.948073

               ph    rainfall
count  100.000000  100.000000
mean     6.790308  158.066295
std      0.417132   25.695086
min      6.020947  115.156401
25%      6.429728  136.011746
50%      6.798626  157.770963
75%      7.132105  181.472018
max      7.493192  199.473564

In [79]:
maize = df.loc[df['label'] == 'maize']
print(maize.describe())

               N           P         K  temperature    humidity          ph  \
count  100.00000  100.000000  100.0000   100.000000  100.000000  100.000000
mean    77.76000   48.440000   19.7900    22.389204   65.092249    6.245190
std     11.94949    8.010498    2.9415     2.679360    5.448699    0.412681
min     60.00000   35.000000   15.0000    18.041855   55.282204    5.513698
25%     67.75000   42.750000   17.0000    19.822579   60.579884    5.854734
50%     76.00000   48.500000   20.0000    22.844456   65.303845    6.259181
75%     87.00000   56.000000   22.0000    24.900640   69.431596    6.602366
max    100.00000   60.000000   25.0000    26.549864   74.829137    6.995844

         rainfall
count  100.000000
mean    84.766988
std     15.547339
min     60.651715
25%     70.384556
50%     83.471553
75%     99.877090
max    109.751538

In [ ]:
df = df.drop('ph',axis=1)

df

In [89]:

X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [90]:
epochs = 100
alpha = 0.1

cost_history, w_history,b_history = training(X_train,y_train,w_init=np.zeros((X_train.shape[1],22)),b_init=0,alpha=alpha,num_eopchs=epochs)
print(f'first cost = {cost_history[0]}, cost after {epochs} and alpha ={alpha} epochs = {cost_history[-1]}')

y_pred = model_m(X_test,w_history[-1],b_history[-1])

cost = compute_costs(X_test,y_test,w_history[-1],b_history[-1])
print(f"cost = {cost}")

first cost = 3.091042453358315, cost after 100 and alpha =0.1 epochs = 1.7700066716216967
cost = 0.687423602524577

In [97]:
epochs = 101
alpha = 0.1

cost_history, w_history,b_history = training(X_train,y_train,w_init=np.zeros((X_train.shape[1],22)),b_init=0,alpha=alpha,num_eopchs=epochs)
print(f'first cost = {cost_history[0]}, cost after {epochs} and alpha ={alpha} epochs = {cost_history[-1]}')

y_pred = model_m(X_test,w_history[-1],b_history[-1])

cost = compute_costs(X_test,y_test,w_history[-1],b_history[-1])
print(f"cost = {cost}")

first cost = 3.091042453358315, cost after 101 and alpha =0.1 epochs = 1.7635004910175183
cost = 0.6878030281399102

In [98]:
df = df.drop('rainfall',axis=1)

df

        N   P   K  temperature   humidity   label
0      90  42  43    20.879744  82.002744    rice
1      85  58  41    21.770462  80.319644    rice
2      60  55  44    23.004459  82.320763    rice
3      74  35  40    26.491096  80.158363    rice
4      78  42  42    20.130175  81.604873    rice
...   ...  ..  ..          ...        ...     ...
2195  107  34  32    26.774637  66.413269  coffee
2196   99  15  27    27.417112  56.636362  coffee
2197  118  33  30    24.131797  67.225123  coffee
2198  117  32  34    26.272418  52.127394  coffee
2199  104  18  30    23.603016  60.396475  coffee

[2200 rows x 6 columns]

In [102]:

X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
X

array([[ 90.        ,  42.        ,  43.        ,  20.87974371,
         82.00274423],
       [ 85.        ,  58.        ,  41.        ,  21.77046169,
         80.31964408],
       [ 60.        ,  55.        ,  44.        ,  23.00445915,
         82.3207629 ],
       ...,
       [118.        ,  33.        ,  30.        ,  24.13179691,
         67.22512329],
       [117.        ,  32.        ,  34.        ,  26.2724184 ,
         52.12739421],
       [104.        ,  18.        ,  30.        ,  23.60301571,
         60.39647474]])

In [103]:
epochs = 101
alpha = 0.1

cost_history, w_history,b_history = training(X_train,y_train,w_init=np.zeros((X_train.shape[1],22)),b_init=0,alpha=alpha,num_eopchs=epochs)
print(f'first cost = {cost_history[0]}, cost after {epochs} and alpha ={alpha} epochs = {cost_history[-1]}')

y_pred = model_m(X_test,w_history[-1],b_history[-1])

cost = compute_costs(X_test,y_test,w_history[-1],b_history[-1])
print(f"cost = {cost}")

first cost = 3.091042453358315, cost after 101 and alpha =0.1 epochs = 1.7635004910175183
cost = 0.6878030281399102

Deleting some features doesnt worked